### ISSUE TITLE
Accuracy is not returned

### ISSUE THREAD

**Issue by Sahil-Mohammad** [mohdsahil2307/Loki#1]

**Comment by Sahil-Mohammad** [comment]
The issue is probably in this [commit](https://github.com/mohdsahil2307/Loki/commit/2aa86b04177060f3577d8b7bf3353f597c5ffb81)

**Comment by Brook98** [comment]
Issue fixed [here](https://github.com/mohdsahil2307/Loki/commit/6154176ceb938a14ccea0a82f3f2e6bdd5bb2e1a)
